title: Public Transport Careers
url: https://ptcareers.gov.sg
favicon: /images/ptcareer_icon.png
colors:
  primary-color: "#000000"
  secondary-color: "#273b8a"
  media-colors:
    - title: media-color-one
      color: "#000000"
    - title: media-color-two
      color: "#f5a623"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Public transport is a key enabler of Singapore's economy. Learn
  more about the industry, the roles and the career opportunities available.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d3474y91fsvb7c.amplifyapp.com
prod: https://master.d3474y91fsvb7c.amplifyapp.com
facebook-pixel: ""
shareicon: /images/behind every journey.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: homepage
